name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t web_app .

      - name: Deploy to Minikube
        run: |
          minikube start
          kubectl apply -f deployment.yaml
          kubectl get pods
